[Mellanox] Add FW dump with new SAI implementation and remove mst dump
shlomibitton/sonic-utilities pull request #13
Opened 2020-11-02 17:15 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

**- What I did**
Add new SAI API to take FW dump (CR space) into 'show techsupport' for Mellanox.
Remove MST dump as it is not required anymore.

**- How I did it**
Add commands to copy FW dump output into techsupport output file, inside "sai_sdk_dump" directory.
Remove commands for MST dump.

**- How to verify it**
Run "show techsupport" with MLNS SAI 1.17.7

**- Previous command output (if the output of a command-line utility has changed)**

**- New command output (if the output of a command-line utility has changed)**

2020-11-03 01:02 UTC, keboliu approved these changes

2020-11-03 08:22 UTC, liat-grozovik reviewed
i dont think this is the way it should work
new sai via the existing api call is gathering more files.
we just need to have them as well.
so why do you need to go to the docker which we already do for sai dump?

2020-11-04 13:04 UTC, liat-grozovik requested changes

2020-11-04 13:04 UTC, liat-grozovik commented on scripts/generate_dump
> +        temp=$(docker exec -it syncd ls -l /tmp | grep sdkdump | awk '{print $9}' | tr -d '\r')
can you use a better name for temp so it will be clear what it stands for?
from the sai implementation there are few files in /tmp. what are they and why only sdkdump? i prefer all the files will be take as we will have more in the future

dont you need {CMD_PREFIX}docker as it is done for the prev?

BTW. the current impl is taking 3 times of mstdump. does it work the same also with the new sai impl?

2020-11-04 13:52 UTC, shlomibitton commented on scripts/generate_dump
> +        temp=$(docker exec -it syncd ls -l /tmp | grep sdkdump | awk '{print $9}' | tr -d '\r')
replaced the "temp" variable to "file_list_string".
{CMD_PREFIX} added.
Current SAI API takes only one dump set, I can loop it 3 times but it will take sdkdump as well, not only the cr space.
all the dump files will be included, "sdkdump" is the prefix of all dump files created with the new API.
SDK should use the same prefix for the other future planned dump files, this way they will be included as well without a need for an additional PR in this matter.
inside '/tmp' directory there are other files except of the dump files and as a tmp directory it is very likely to have some other files in the future as well. this way we can distinguish between needed files and unnecessary files.

2020-11-04 13:55 UTC, liat-grozovik commented
This is a problem
But the question is if the 3 times comes from sdk and only sai does not do It of the sai is required to call the same api 3 times.
This is something you should not do in the nos.

Please send an email to Yanina and have Itai on the loop.

Originally the reason for 3 calls was to have the fw team the ability to see if something changed. Previously they defined the flow.
If now it is not, then sai needs to do it. not nos.
Nos is transparent here.

From: shlomibitton <notifications@github.com>
Sent: Wednesday, November 4, 2020 3:53 PM
To: shlomibitton/sonic-utilities <sonic-utilities@noreply.github.com>
Cc: Liat Grozovik <liatg@nvidia.com>; Comment <comment@noreply.github.com>
Subject: Re: [shlomibitton/sonic-utilities] [Mellanox] Add FW dump with new SAI implementation and remove mst dump (#13)


@shlomibitton commented on this pull request.

________________________________

In scripts/generate_dump<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshlomibitton%2Fsonic-utilities%2Fpull%2F13%23discussion_r517357200&data=04%7C01%7Cliatg%40nvidia.com%7C411b699ad8c0478aa93608d880c8eb7f%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637400947722288805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XEHqHh2oNtYH7eV4L6K11Ovu8dEY2IQn%2BdkkvOp9Xnw%3D&reserved=0>:

> @@ -427,12 +427,12 @@ main() {

         ${CMD_PREFIX}docker exec -it syncd saisdkdump -f $sai_dump_filename

         ${CMD_PREFIX}docker exec syncd tar Ccf $(dirname $sai_dump_filename) - $(basename $sai_dump_filename) | tar Cxf /tmp/ -

         save_file $sai_dump_filename sai_sdk_dump true

-

-        local mst_dump_filename="/tmp/mstdump"

-        local max_dump_count="3"

-        for i in $(seq 1 $max_dump_count); do

-            ${CMD_PREFIX}/usr/bin/mstdump /dev/mst/mt*conf0 > "${mst_dump_filename}${i}"

-            save_file "${mst_dump_filename}${i}" mstdump true

+        temp=$(docker exec -it syncd ls -l /tmp | grep sdkdump | awk '{print $9}' | tr -d '\r')

replaced the "temp" variable to "file_list_string".
{CMD_PREFIX} added.
Current SAI API takes only one dump set, I can loop it 3 times but it will take sdkdump as well, not only the cr space.
all the dump files will be included, "sdkdump" is the prefix of all dump files created with the new API.
SDK should use the same prefix for the other future planned dump files, this way they will be included as well without a need for an additional PR in this matter.
inside '/tmp' directory there are other files except of the dump files and as a tmp directory it is very likely to have some other files in the future as well. this way we can distinguish between needed files and unnecessary files.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshlomibitton%2Fsonic-utilities%2Fpull%2F13%23discussion_r517357200&data=04%7C01%7Cliatg%40nvidia.com%7C411b699ad8c0478aa93608d880c8eb7f%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637400947722288805%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XEHqHh2oNtYH7eV4L6K11Ovu8dEY2IQn%2BdkkvOp9Xnw%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKTABA35BR7PXXFI562XOHTSOFMC7ANCNFSM4THXQECQ&data=04%7C01%7Cliatg%40nvidia.com%7C411b699ad8c0478aa93608d880c8eb7f%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637400947722298802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7K7r%2B6oFvsSNxTxF5T43UwLzm1aggICPPC%2BJxgR9EOQ%3D&reserved=0>.

2020-11-04 14:04 UTC, shlomibitton commented
@liat-grozovik 
Previously with mst dump it was hard coded in the script to take it 3 times.
If this is the requirement, SAI should make the change in the API not SDK IMO.
The SAI API is one call which takes sdk + cr space dumps, if we need 3 times only "cr space" it should be done on SAI API.

2020-11-04 14:06 UTC, liat-grozovik commented
Cool. please open a bug to Itai so he can fix it

From: shlomibitton <notifications@github.com>
Sent: Wednesday, November 4, 2020 4:05 PM
To: shlomibitton/sonic-utilities <sonic-utilities@noreply.github.com>
Cc: Liat Grozovik <liatg@nvidia.com>; Mention <mention@noreply.github.com>
Subject: Re: [shlomibitton/sonic-utilities] [Mellanox] Add FW dump with new SAI implementation and remove mst dump (#13)


@liat-grozovik<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fliat-grozovik&data=04%7C01%7Cliatg%40nvidia.com%7C286c9cf2511b4d86310808d880caa96a%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637400955204801261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=i3bQq3uSeawE229iDqKjuJODstME3%2F7PnvhzlZ1tPsc%3D&reserved=0>
Previously with mst dump it was hard coded in the script to take it 3 times.
If this is the requirement, SAI should make the change in the API not SDK IMO.
The SAI API is one call which takes sdk + cr space dumps, if we need 3 times only "cr space" it should be done on SAI API.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshlomibitton%2Fsonic-utilities%2Fpull%2F13%23issuecomment-721750687&data=04%7C01%7Cliatg%40nvidia.com%7C286c9cf2511b4d86310808d880caa96a%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637400955204801261%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=s9vWP7ZoUu8SLNRsNm343%2BNu1cKcClnGzrPNmNXw9eA%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAKTABAY7KPCJRDXUK66CAWDSOFNRFANCNFSM4THXQECQ&data=04%7C01%7Cliatg%40nvidia.com%7C286c9cf2511b4d86310808d880caa96a%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C637400955204811254%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DzQX5faSIw2jn1OPF6d1udJ6s8ePhe5PwCnidEaGXr8%3D&reserved=0>.

2020-11-12 16:26 UTC, liat-grozovik commented
@shlomibitton itai mentioned he calls the sdk api 3 times. so we just need to see if this is reflected in the logs.
if so it is approved and you can upstream it.

2020-12-09 14:58 UTC, closed without merging