[fast-reboot] Fix dump script to support PortChannels in a VLAN group
shlomibitton/sonic-utilities pull request #16
Opened 2021-01-13 13:38 UTC by shlomibitton

**- What I did**
Add PortChannels to the list of interfaces (port_id_2_iface) to support FDB dump for PortChannel in a VLAN group.
Fixed issue https://github.com/Azure/sonic-buildimage/issues/4793

**- How I did it**
* Get LAG ID from the DB.
* Find the LAG name from APP DB.
* Add it to the list of 'port_id_2_iface' to be used.

**- How to verify it**
Reproduce the issue mentioned on this PR and try to run fast-reboot with this fix.

**- Previous command output (if the output of a command-line utility has changed)**
Traceback:
src_ifs = {map_mac_ip_per_vlan[vlan_name][dst_mac] for vlan_name, dst_mac, _ in arp_entries}
#012 KeyError: 'b8:59:9f:a8:e2:00'

**- New command output (if the output of a command-line utility has changed)**
Success .

2021-01-14 10:41 UTC, stepanblyschak requested changes

2021-01-14 10:41 UTC, stepanblyschak commented on scripts/fast-reboot-dump.py
> +def get_lag_name(member_name, app_db):
I suggest the following function signature:
```suggestion
def get_lag_by_member(app_db, member_name):
```

2021-01-14 10:41 UTC, stepanblyschak commented on scripts/fast-reboot-dump.py
> +    keys = app_db.keys(app_db.APPL_DB, 'LAG_MEMBER_TABLE:PortChannel*')
It is not necessary to assume that LAG will be prefixed with PortChannel. Instead I think 'LAG_MEMBER_TABLE:*' will work just fine here.

2021-01-14 10:41 UTC, stepanblyschak commented on scripts/fast-reboot-dump.py
> +        entry = key.split(":")
I suggest more verbose way to parse the key:
```suggestion
        _, lag_name, lag_member_name = key.split(":")
```

2021-01-14 13:08 UTC, shlomibitton commented on scripts/fast-reboot-dump.py
> +def get_lag_name(member_name, app_db):
Fixed

2021-01-14 13:08 UTC, shlomibitton commented on scripts/fast-reboot-dump.py
> +        entry = key.split(":")
Fixed

2021-01-14 13:08 UTC, shlomibitton commented on scripts/fast-reboot-dump.py
> +    keys = app_db.keys(app_db.APPL_DB, 'LAG_MEMBER_TABLE:PortChannel*')
Fixed

2021-01-15 15:32 UTC, stepanblyschak approved these changes

2021-01-31 07:43 UTC, closed without merging