[DHCP] Add DHCP relay CLI support for IPv6
shlomibitton/sonic-utilities pull request #19
Opened 2021-03-31 10:56 UTC by shlomibitton

Signed-off-by: Shlomi Bitton <shlomibi@nvidia.com>

#### What I did
Adapt config/show CLI commands to support DHCPv6 relay feature.
Add a new function to 'cli common' to check the type of IP address.

#### How I did it
Edit 'vlan' config/show scripts to support 'dhcpv6_servers' along to the 'dhcp_servers'.

#### How to verify it
Build an image with this PR: https://github.com/shlomibitton/sonic-buildimage/pull/49
Use the CLI to add/remove DHCP servers with IPv6.

#### Previous command output (if the output of a command-line utility has changed)
-

#### New command output (if the output of a command-line utility has changed)
-

2021-04-27 12:56 UTC, nazariig commented
@shlomibitton do we need a UTs?

2021-04-27 13:03 UTC, shlomibitton commented
> @shlomibitton do we need a UTs?

Yes we do, I will add it.

2021-04-27 13:37 UTC, nazariig commented on show/vlan.py
> +            pass
@shlomibitton this seem to be redundant/complicated. How about this:
```python
if 'dhcp_servers' in vlan_dhcp_helper_data[key].keys():
    dhcp_servers = vlan_dhcp_helper_data[key]['dhcp_servers']
    if dhcp_servers:
        vlan_dhcp_helper_dict[key.strip('Vlan')] += dhcp_servers
```
or
```python
dhcp_servers = vlan_dhcp_helper_data[key]['dhcp_servers'] if 'dhcp_servers' in vlan_dhcp_helper_data[key].keys() else []
if dhcp_servers:
    vlan_dhcp_helper_dict[key.strip('Vlan')] += dhcp_servers
```

2021-04-27 13:49 UTC, nazariig commented on utilities_common/cli.py
> +    try:
@shlomibitton suggest to separate code with some newlines:
```python
def ipaddress_type(val):
    """ Return the IP address type """    
    if not val:
        return None

    try:
        ip_addr = netaddr.IPAddress(str(val))
    except netaddr.core.AddrFormatError:
        return None

    return ip_addr.version
```

2021-04-27 13:49 UTC, nazariig commented on utilities_common/cli.py
> +    import netaddr
@shlomibitton any reason not to import at module level?

2021-05-12 09:54 UTC, nazariig approved these changes

2021-05-23 14:42 UTC, liat-grozovik requested changes
please also update https://github.com/Azure/sonic-utilities/blob/master/doc/Command-Reference.md#dhcp-relay-config-commands

2021-05-23 14:42 UTC, liat-grozovik commented on config/vlan.py
> +                return
instead of return maybe better to move the the next and handle what you can?

2021-05-23 14:42 UTC, liat-grozovik commented on config/vlan.py
> +                return
same as above

2021-05-23 14:42 UTC, liat-grozovik commented on config/vlan.py
> +    # verify all ip addresses are valid
why do you need to verify they are valid?
if the user provided a wrong ip it will not find it in the db. reduce for loop :-)

2021-05-23 14:42 UTC, liat-grozovik commented on config/vlan.py
> +    exist_dhcp_servers = vlan.get('dhcp_servers', [])
will it be better to have a function for add/remove a list instead of 2 different loops in one function?

2021-05-23 14:42 UTC, liat-grozovik commented on config/vlan.py
> +        vlan['dhcp_servers'] = exist_dhcp_servers
does this replace the list on the config db? will it trigger even of change although and then will be removed from logic?

2021-05-23 14:42 UTC, liat-grozovik commented on tests/vlan_test.py
can you confirm there is also a negative test in unit test? meaning we should verify that the behaviour of wrong IP add/del for ipv4 and ipv6.
as for the new approach i suggested that one out of the x ips is not valid, cont. there is also a need to cover it in unit test.

2021-05-24 16:00 UTC, shlomibitton commented on config/vlan.py
> +                return
Fixed, a message will print out to inform the user if one of the addresses is already exist.
All other addresses will be added, a restart to the service will take place **only** if new addresses added.

2021-05-24 16:01 UTC, shlomibitton commented on config/vlan.py
> +                return
same as the above

2021-05-24 16:01 UTC, shlomibitton commented on config/vlan.py
> +    # verify all ip addresses are valid
Fixed, and optimized to run on one loop for the whole operation.

2021-05-24 16:01 UTC, shlomibitton commented on config/vlan.py
> +    exist_dhcp_servers = vlan.get('dhcp_servers', [])
Fixed, and optimized to run on one loop for the whole operation.

2021-05-24 16:02 UTC, shlomibitton commented on config/vlan.py
> +        vlan['dhcp_servers'] = exist_dhcp_servers
The DB will change only if all logical checks have passed and then yes, it will replace the list in config DB.

2021-05-24 16:04 UTC, shlomibitton commented on tests/vlan_test.py
There is actually, but the package used to verify it is checking only if each ascii value of IP address is in range and not a wrong string, I have improved the current test to verify this as well.

2021-05-24 16:04 UTC, shlomibitton commented
> please also update https://github.com/Azure/sonic-utilities/blob/master/doc/Command-Reference.md#dhcp-relay-config-commands

@liat-grozovik all comments addressed, CLI reference updated.
please review, thanks

2021-05-26 13:19 UTC, liat-grozovik approved these changes

2021-07-18 11:53 UTC, closed without merging